name: Simple SSH Access

on:
  workflow_dispatch:

jobs:
  ssh-access:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Setup SSH Server
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server
          echo "root:password123" | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo service ssh restart

      - name: Show Connection Info
        run: |
          IP=$(hostname -I | awk '{print $1}')
          echo "🟢 SSH READY!"
          echo "IP: $IP"
          echo "User: root"
          echo "Password: password123"
          echo ""
          echo "🚀 Connect with: ssh root@$IP"

      - name: Keep Alive
        run: |
          echo "⏰ Waiting for SSH connections (2 hours max)..."
          sleep 7200
