name: Simple Tailscale SSH - Fixed

on:
  workflow_dispatch:

jobs:
  ssh-simple:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Setup Tailscale & SSH
        run: |
          # Install Tailscale
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --auth-key=${{ secrets.TAILSCALE_AUTH_KEY }}
          
          # Setup SSH dengan user baru
          sudo apt install -y openssh-server
          sudo useradd -m -s /bin/bash myuser
          echo "myuser:password123" | sudo chpasswd
          sudo usermod -aG sudo myuser
          
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: Show Connection Info
        run: |
          sleep 10
          IP=$(tailscale ip -4)
          echo ""
          echo "🚀 SSH READY - 6 JAM"
          echo "========================"
          echo "IP: $IP"
          echo "User: myuser"
          echo "Password: password123"
          echo "========================"
          echo ""
          echo "Konek dengan:"
          echo "ssh myuser@$IP"

      - name: Wait 6 hours
        run: |
          echo "⏳ Menunggu koneksi SSH selama 6 jam..."
          sleep 21600
          echo "✅ Waktu habis - Workflow selesai"
