name: Simple Tailscale SSH

on:
  workflow_dispatch:

jobs:
  ssh-simple:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Setup Tailscale & SSH
        run: |
          # Install Tailscale
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --auth-key=${{ secrets.TAILSCALE_AUTH_KEY }}
          
          # Setup SSH
          sudo apt install -y openssh-server
          echo "ubuntu:tailscale123" | sudo chpasswd
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sssd_config
          sudo service ssh restart

      - name: Show Info
        run: |
          sleep 5
          IP=$(tailscale ip -4)
          echo "🚀 SSH READY - 6 JAM"
          echo "IP: $IP"
          echo "User: ubuntu"
          echo "Pass: tailscale123"
          echo ""
          echo "Konek: ssh ubuntu@$IP"

      - name: Wait 6 hours
        run: sleep 21600
